### ISSUE TITLE
Use that pull board, the other it's not very useful, if not useless.

### ISSUE THREAD

**Issue by TDD788** [Mizumo-prjkt/A12-Exynos-recovery-devtree#3]
decompress the file on your PC/phone and upload it to the ofox repository
[Internal storage.zip](https://github.com/SUFandom/A12-Exynos-recovery-devtree/files/14494596/Internal.storage.zip)

you need to edit the board according to your DT

**Comment by Mizumo-prjkt** [comment]
allowed most flags

but there are some that are kept
